name: Deploy

on:

  push:

    branches:

      - main

jobs:

  build:

    name: gitops ci-cd

    runs-on: ubuntu-latest

    steps:

    - name: push image tag to env repo

      env:

        PAT: ${{secrets.PUSH_TOKEN}}

      run: |-

        git clone https://${PAT}@github.com/umesh-cloudside/env-repo.git -b app1

        cd env-repo

        git_hash=$(git rev-parse --short "$GITHUB_SHA")

        echo the new image tag will be $git_hash

        tag=$(cat deploy.yaml | grep 'asia-south1-docker.pkg.dev/ak-dev-apps/repo-dev-apps/coupon-service-dev:' | awk -F: '{print $0=$3}')

        echo the old image tag is $tag

        sed -i 's/'"${tag}"'/'"${git_hash}"'/' deploy.yaml

        git config --global user.name "umesh-cloudside"

        git config --global user.email "umesh@thecloudside.com"

        git remote set-url origin https://umesh-cloudside:${PAT}@github.com/umesh-cloudside/env-repo.git

        git add deploy.yaml

        git commit -m "image version updated in deployment file"

        git push 

        echo the new image tag $git_hash is updated
