name: deploy-gcp-dev-release
on:
  push:
    branches:
      - 'release/dev'

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: github-actions-gke
      PROJECT_ID: cloudside-academy 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$(git rev-parse --short "$GITHUB_SHA")
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$(git rev-parse --short "$GITHUB_SHA")

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest asia-south1-docker.pkg.dev/$PROJECT_ID/repo-dev-apps/$IMAGE_NAME:$(git rev-parse --short "$GITHUB_SHA")
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/repo-dev-apps/$IMAGE_NAME:$(git rev-parse --short "$GITHUB_SHA")
        
    - name: push image tag to env repo
      env:
        PAT: ${{secrets.ENV_PAT}}
      run: |-
        git clone https://${PAT}@github.com/apnaklub-tech/k8s-env.git -b order-service-dev
        cd k8s-env
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo the new image tag will be $git_hash
        tag=$(cat deployment.yaml | grep 'asia-south1-docker.pkg.dev/ak-dev-apps/repo-dev-apps/order-service-dev:' | awk -F: '{print $0=$3}')
        echo the old image tag is $tag
        sed -i 's/'"${tag}"'/'"${git_hash}"'/' deployment.yaml
        git config --global user.name "umesh-cloudside"
        git config --global user.email "umesh@thecloudside.com"
        git remote set-url origin https://umesh-cloudside:${PAT}@github.com/apnaklub-tech/k8s-env.git
        git add deployment.yaml
        git commit -m "image version updated in deployment file"
        git push 
        echo the new image tag $git_hash is updated

