name: Deploy

on:

  push:

    branches:

      - main

jobs:

  build:

    name: gitops ci-cd

    runs-on: ubuntu-latest

    steps:

    - name: push image tag to abcd repo

      env:

        PAT: ${{secrets.PAT}}

      run: |-

        https://github.com/aamir-34/abcd-repo.git

        cd abcd-repo

        git_hash=$(git rev-parse --short "$GITHUB_SHA")

        echo the new image tag will be $git_hash

        tag=$(cat deploy.yaml | gcr.io/cloudside-academy/github-actions-gke-image | awk -F: '{print $0=$3}')

        echo the old image tag is $tag

        sed -i 's/'"${tag}"'/'"${git_hash}"'/' deploy.yaml

        git config --global user.name "aamir-34"

        git config --global user.email "aq702654@gmail.com"

        git remote set-url origin https://aamir-34:${PAT}@github.com/aamir-34/abcd-repo.git

        git add deploy.yaml

        git commit -m "image version updated in deployment file"

        git push 

        echo the new image tag $git_hash is updated
