name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: work-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: github-actions-gke
  IMAGE: github-actions-gke-image10
  TAG: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
      - name: clone repo
        run: |-
           git clone https://github.com/aamir-34/abcd-repo.git
            cd abcd-repo
           git_hash=$(git rev-parse --short "$GITHUB_SHA")

           echo the new image tag will be $git_hash

           tag=$(cat deployment.yaml | grep 'us-central1-docker.pkg.dev/ ${{secrets.GKE_PROJECT}}/abcd-repo/order-service-dev:' | awk -F: '{print $0=$3}')

           echo the old image tag is $tag

           git config --global user.name "aamir-34"

           git config --global user.email "aq702654@gmail.com"

           git add deployment.yaml

           git commit -m "image version updated in deployment file"

            git push 

           echo the new image tag $git_hash is updated

